/**
 * Single source of truth for the plain-language glossary used across the app.
 *
 * The same definitions power the Getting Started "Terms glossary" list AND the
 * inline hover tooltips on the Dashboard and Tax Summary pages (R41.2), so the
 * wording never drifts between where a term is defined and where it is used.
 *
 * Each entry has a stable `id` (used by the <GlossaryTerm> component to look up
 * a definition) plus the human `term` label and its `def`.
 */
export interface GlossaryEntry {
  id: string;
  term: string;
  def: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  { id: "ear", term: "EAR (Effective Annual Rate)", def: "The true annualised yield once compounding is included. MMFs quote a net EAR after the manager's fee; the tracker applies 15% withholding tax on top." },
  { id: "wht", term: "WHT (Withholding Tax)", def: "Tax deducted at source before you receive interest. In Kenya it is 15% on MMF, T-bill and FXD income. IFB (infrastructure bond) interest is tax-exempt." },
  { id: "tbill", term: "T-Bill (Treasury Bill)", def: "A short-term government discount instrument (91, 182 or 364 days). You pay less than face value up front (the purchase price), receive no coupons, and are repaid the full face value at maturity. The discount (face minus price) is your entire return, and 15% withholding tax applies only to that discount." },
  { id: "ifb", term: "IFB (Infrastructure Bond)", def: "A long-dated government bond funding infrastructure. Its coupon is tax-exempt, making its net yield higher than a comparable taxable bond." },
  { id: "fxd", term: "FXD (Fixed-Coupon Treasury Bond)", def: "A government bond paying a fixed semi-annual coupon (around 12.35% gross). The 15% WHT is deducted before the coupon reaches you." },
  { id: "call-deposit", term: "Call deposit", def: "A liquid bank deposit that earns interest while remaining accessible on short notice (no fixed maturity). Rates are usually negotiable for larger balances and sit between an ordinary savings account and a fixed deposit." },
  { id: "fixed-deposit", term: "Fixed deposit", def: "A bank deposit locked for a set term at an agreed rate; principal plus interest is paid back at maturity. Breaking it early usually forfeits some interest (an early-break penalty)." },
  { id: "ordinary-savings", term: "Ordinary / regular savings", def: "An everyday bank savings account that is fully liquid and pays a modest, variable rate. Easy to access but typically the lowest yield of the bank options." },
  { id: "target-savings", term: "Target / goal savings", def: "A savings account tied to a goal and a target date. It usually pays more than ordinary savings, but withdrawing before the target date may forfeit some interest." },
  { id: "tiered-savings", term: "Tiered / high-yield savings", def: "A liquid savings account whose interest rate rises as your balance crosses set tiers, so larger balances earn a higher rate while staying accessible." },
  { id: "early-break", term: "Early-break penalty", def: "Interest you forfeit if you withdraw a term deposit (fixed or goal savings) before its maturity date. It is the cost of breaking the lock early, so term deposits should hold money you will not need until maturity." },
  { id: "concentration", term: "Issuer concentration / diversification", def: "How much of your money sits with any single bank or issuer. Spreading deposits across issuers limits credit risk; this tracker caps any one bank at roughly a quarter of the portfolio. Government securities are exempt because they are sovereign-backed." },
  { id: "sovereign-risk", term: "Sovereign vs bank credit risk", def: "Government securities (T-bills, bonds) are backed by the state and carry sovereign risk; bank deposits depend on the bank staying solvent. When yields are close, the tracker prefers the government instrument for its stronger backing." },
  { id: "rollover", term: "Redeployment / rollover at maturity", def: "When a deposit or security matures, its principal and interest return to the MMF and are re-invested into the best eligible instrument that still matures before your goal date - or kept in the MMF if nothing fits. The Month Ledger shows each move in plain language." },
  { id: "yield-max", term: "Yield-maximising allocation", def: "The rule the engine uses to place each tranche of cash: keep the safety floor liquid, then choose the eligible instrument with the highest net-of-tax yield that matures before your goal, applying a small preference for government backing and a per-bank concentration cap." },
  { id: "duration", term: "Duration", def: "A measure of how sensitive a bond's price is to interest-rate changes. Longer duration means larger price swings when rates move." },
  { id: "gross-yield", term: "Gross yield", def: "The headline interest rate before any tax is taken out. It looks higher than what you actually keep." },
  { id: "net-yield", term: "Net yield", def: "What you actually keep after withholding tax is deducted. Net = gross x (1 - WHT). This is the number that matters for reaching your goal." },
  { id: "day-count", term: "Day-count basis", def: "The convention for counting days in a year when calculating interest (usually Actual/365 in Kenya). It decides how a daily interest figure is derived from an annual rate." },
  { id: "daily-compounding", term: "Daily compounding", def: "Interest is added to your balance every day, so the next day's interest is calculated on a slightly larger balance. Over a year this beats simple (once-a-year) interest." },
  { id: "mmf", term: "MMF (Money Market Fund)", def: "A regulated fund that pools investors' money into safe, short-term instruments. It pays interest daily, is usually withdrawable within 1-3 days, and has no early-exit penalty." },
  { id: "savings-deposit", term: "Savings deposit", def: "An ordinary or instant-access bank account paying a variable, usually lower, interest rate. Easy to access but often the lowest yield." },
  { id: "coupon", term: "Coupon", def: "The interest payment a bond makes to you, usually twice a year, expressed as a percentage of the bond's face value." },
  { id: "maturity", term: "Maturity", def: "The date a security (T-bill, bond or fixed deposit) ends and the principal is returned to you. After maturity the cash is liquid again." },
  { id: "tenor", term: "Tenor", def: "How long a security or deposit runs from start to maturity - e.g. a 182-day T-bill has a 182-day tenor." },
  { id: "sweep", term: "Sweep", def: "Moving surplus cash out of the MMF into a higher-yielding security (such as a T-bill or bond) once you have more than your safety floor. This tracker sweeps automatically in the projection." },
  { id: "safety-floor", term: "Safety floor", def: "The minimum cash kept liquid in the MMF before any sweep. It is your working buffer so you are never forced to break a locked instrument early." },
  { id: "liquidity", term: "Liquidity", def: "How quickly an asset can be turned into spendable cash without loss. MMF and call deposits are highly liquid; fixed deposits and bonds are locked until maturity." },
  { id: "phases", term: "Phases", def: "The four stages of the plan - Foundation, Growth, De-risking and Final liquidity - that shift the mix from building up, to maximising yield, to locking in gains, to holding cash for the goal date." },
  { id: "step-up", term: "Step-up", def: "A scheduled increase in your monthly contribution (e.g. +KES 5,000 every 6 months) that accelerates progress toward the target." },
  { id: "reconciliation", term: "Reconciliation", def: "An independent cross-check that the 'today' value of your portfolio agrees across every source - sum of holdings, the projection engine, the dashboard total and the net-worth card. When they disagree, the mismatch is shown so the cause can be traced." },
  { id: "blended-yield", term: "Blended yield", def: "The single weighted-average yield across all your holdings combined, weighting each instrument by how much money sits in it." },
  { id: "tax-drag", term: "Tax drag", def: "The amount of yield you lose to withholding tax - the gap between your blended gross yield and your blended net yield. Tax-exempt IFBs reduce tax drag." },
  { id: "net-worth", term: "Net worth", def: "The total of everything you actually hold right now - primary MMF, any secondary MMFs, bank deposits, CBK securities and other assets - based on real recorded money, not projections." },
  { id: "rediscounting", term: "Rediscounting / secondary-market sale", def: "Selling a government security (T-bill or bond) before its maturity date on the secondary market rather than holding it to maturity. The price is set by current market rates, so you may receive more or less than face value. Holding to maturity is the normal path; rediscounting is the early-exit option when you need the cash sooner." },
  { id: "coupon-class", term: "Coupon class / tenor", def: "Government bonds are grouped by their maturity length (tenor). FXD and IFB bonds are issued at standard tenors (e.g. 2, 5, 10, 15, 20 years), and each tenor carries its own coupon rate. This tracker keeps a per-tenor rate so a 10-year bond and a 20-year bond can earn different coupons." },
  { id: "fxd-vs-ifb", term: "FXD vs IFB", def: "Two kinds of Treasury bond. An FXD (Fixed-Coupon Treasury Bond) pays a fixed coupon that is taxed at 15% WHT. An IFB (Infrastructure Bond) funds infrastructure and its coupon is fully tax-exempt, so an IFB usually keeps more of its yield than an FXD at the same gross rate." },
  { id: "tiered-wht", term: "Tiered WHT", def: "Withholding tax that changes with the bond's tenor. In Kenya, Treasury bond coupons are taxed at 15% for tenors under 10 years and 10% for tenors of 10 years or more. IFB coupons are exempt regardless of tenor. The tracker applies the correct tier automatically." },
  { id: "accrued-interest", term: "Accrued interest", def: "Interest that has built up on a holding but has not yet been paid out or compounded. For MMF and bank deposits it grows daily since the start date. For a coupon bond (FXD/IFB) it is measured only since the LAST coupon date - not since the bond was issued - because each coupon is paid out every six months and resets the count to zero. It becomes cash you keep when the instrument pays out or you withdraw." },
  { id: "indicative-rate", term: "Indicative vs negotiated rate", def: "An indicative rate is the bank's published guide rate for a deposit; a negotiated rate is what you actually agree, often higher for larger balances. When you record a bank deposit the tracker pre-fills the indicative rate, but you can override it with the rate you negotiated." },
  { id: "maturity-redeployment", term: "Maturity redeployment", def: "When a security or deposit matures, its principal plus interest returns to the MMF and is automatically re-invested into the best eligible instrument that still matures before your goal date (or kept liquid if nothing fits). This keeps idle cash working without manual reinvestment." },
  { id: "discount-instrument", term: "Discount instrument", def: "A security you buy for LESS than its face value, receive nothing in between, and redeem at full face value at maturity. The gap between what you pay and the face value is your entire return. T-bills and zero-coupon bonds work this way - unlike coupon bonds, which pay you interest along the way." },
  { id: "face-value", term: "Face value (par / redemption value)", def: "The fixed amount the government repays you at maturity - e.g. KES 100,000. For a discount instrument you pay less than this up front; for a coupon bond you usually pay the face value (par) and the coupons are your return." },
  { id: "purchase-price", term: "Purchase price", def: "The cash you actually pay up front for a security. For a T-bill or zero-coupon bond this is below face value (the discounted price); for a coupon bond it is normally the face value (par)." },
  { id: "discount-return", term: "Discount (the return)", def: "Face value minus purchase price. For a T-bill or zero-coupon bond this discount IS the interest you earn - there are no separate coupon payments. Withholding tax applies only to this discount, never to the full face value." },
  { id: "accretion", term: "Accretion", def: "The gradual pull of a discount instrument's value up toward its face value as it ages. It starts at the purchase price and rises to face by maturity. Accretion is not the same as MMF compounding and the value never grows above face." },
  { id: "par-value", term: "Par value", def: "A bond priced at par means its purchase price equals its face value. Coupon bonds (FXD/IFB) are typically issued at par; discount instruments (T-bills, zero-coupon bonds) are issued below par." },
  { id: "coupon-bond", term: "Coupon bond", def: "A bond bought at (or near) face value that pays you regular interest - the coupon - usually twice a year, and returns the principal at maturity. FXD and IFB bonds are coupon bonds, in contrast to discount instruments." },
  { id: "zero-coupon", term: "Zero-coupon bond", def: "A longer-dated discount instrument: you buy it well below face value, it pays no coupons, and it redeems at full face value years later. Because the gap is large over several years, its price is computed with compound interest (face divided by (1+rate)^years)." },
  { id: "floating-rate", term: "Floating-rate bond", def: "A bond whose coupon is not fixed but resets periodically to a benchmark rate (such as the 91-day T-bill rate) plus a fixed margin. When the benchmark moves, the next coupon moves with it. Coupons are taxed like an FXD." },
  { id: "benchmark-rate", term: "Benchmark / reference rate", def: "The published market rate a floating-rate instrument is pegged to - in Kenya usually the 91-day Treasury bill rate. The instrument's coupon is this benchmark plus an agreed margin, recalculated at each reset." },
  { id: "yield-vs-coupon", term: "Yield vs coupon", def: "The coupon is the fixed payment rate printed on a bond; the yield is your actual return given the price you paid. If you buy a bond below par, your yield is higher than its coupon; above par, lower. For discount instruments there is no coupon - the yield comes entirely from the discount." },
  { id: "semi-annual-coupon", term: "Semi-annual coupon", def: "Most Kenyan Treasury bonds pay their coupon twice a year (every six months). A 12% annual coupon is therefore paid as two 6% instalments, each net of withholding tax for taxable bonds." },
  { id: "wht-discount-vs-coupon", term: "WHT: discount vs coupon", def: "Withholding tax is charged differently by instrument. On a T-bill or zero-coupon bond, the 15% WHT applies to the discount (face minus price) at maturity. On a coupon bond, WHT is deducted from each coupon as it is paid (15% for tenors under 10 years, 10% for 10 years or more; IFB is exempt)." },
  // ── Round 62: allocation policy, concentration caps & liquid diversification ──
  { id: "coupon-bond-current-value", term: "Current value of a coupon bond", def: "What an FXD or IFB bond is worth to you today: its face (par) value plus only the coupon accrued SINCE THE LAST coupon date - not since the bond was issued. Each semi-annual coupon is paid into your MMF and resets the accrual to roughly zero, so the bond's current value never drifts far above face. For FXD the accrued portion is shown net of withholding tax; IFB is tax-exempt. This keeps the register's Current Value, the Dashboard's Total Current Value and Unrealised Gain in agreement with the face value used in net worth." },
  { id: "allocation-policy", term: "Allocation policy", def: "How you want the engine to place your liquid cash. Balanced (default) diversifies across eligible homes and respects your concentration caps. Yield-first / concentrate relaxes the caps toward 100% and parks everything in the single highest net-yield home (e.g. all in the MMF when it out-yields a call deposit) - higher return, but more money with one institution; choosing it requires a recorded risk acknowledgment. Custom lets you set your own per-issuer and per-type caps and keeps them exactly as entered." },
  { id: "concentration-cap-override", term: "Concentration cap override", def: "When you record real money that pushes one issuer or instrument type above its cap, the tracker does not block you - it shows an inline prompt and, if you proceed, logs your acknowledgment (which issuer/type, the percentage, and the timestamp) in Change History. This only ever happens for actual recorded holdings, never for the engine's projected sweeps." },
  { id: "per-issuer-vs-per-type-cap", term: "Per-issuer cap vs per-type cap", def: "Two different limits. The per-issuer cap (default 25%) limits how much of your net worth sits with any one bank or institution - protecting against a single institution failing. The per-type cap (default 60%) limits how much sits in any one instrument family (T-bill, IFB, FXD, bank, MMF) - protecting against one product type dominating. Government securities are sovereign-backed and exempt from the issuer cap." },
  { id: "liquid-reserve-diversification", term: "Liquid-reserve diversification", def: "Spreading your spendable (liquid) cash across several homes - the primary MMF, any secondary MMFs and liquid bank accounts (call deposit, savings) - so no single institution holds it all. Each month, after term securities are bought, the engine ranks the liquid homes by net yield and fills each up to its cap, parking any overflow in the next-best home. Fixed deposits and government securities are excluded because they are locked, not liquid." },
  { id: "kdic-insurance", term: "KDIC insurance", def: "The Kenya Deposit Insurance Corporation guarantees bank deposits up to KES 500,000 per depositor per bank. Spreading large balances across multiple banks keeps more of your money inside this cover. Money market funds are NOT deposit-insured - they are regulated unit trusts whose protection comes from diversification and oversight, not KDIC - which is why the tracker treats MMF concentration as a separate consideration from bank concentration." },
  { id: "mmf-uninsured", term: "MMF deposits are not KDIC-insured", def: "Money held in a money market fund is NOT covered by KDIC deposit insurance, which only protects bank deposits (up to KES 500,000 per depositor per bank). An MMF is a regulated unit trust: its safeguards are diversification, daily liquidity and CMA oversight, not a state guarantee. So a large MMF balance carries the fund manager's credit and operational risk with no insured floor - a real liability the plan should not gloss over, especially when the end-state concentrates heavily in one fund." },
  // ── Round 69: per-type cap (duration/liquidity guardrail), acknowledgment alias ──
  { id: "per-type-cap", term: "Per-type cap (duration / liquidity guardrail)", def: "A limit (default 60%) on how much of your net worth sits in any one instrument FAMILY - T-bills, IFB, FXD, bank deposits or MMF. Unlike the per-issuer cap, this is not about credit risk: all CBK securities share the same sovereign issuer, so the per-type cap is a duration and liquidity guardrail - it stops any single tenor profile (e.g. long FXD bonds) from dominating and locking up too much of your money at once. Because a held bond cannot be 'moved' without rediscounting it on the secondary market at a cost, a breach from securities you already hold is treated as a forward rule: the engine simply stops buying more of that type, and the breach clears on its own as those lots mature. Selling early is only suggested when the breach will not clear within your horizon." },
  { id: "per-issuer-cap", term: "Per-issuer cap (credit diversification)", def: "A limit (default 25%) on how much of your net worth sits with any one bank or institution. This is a credit-risk control: if a single institution failed, your loss is capped at this share. Government securities (T-bills, IFB, FXD) are sovereign-backed and exempt. Contrast with the per-type cap, which limits instrument families for duration/liquidity reasons rather than credit." },
  { id: "concentration-cap-acknowledgment", term: "Concentration-cap acknowledgment", def: "Accepting a concentration-cap breach on real money you actually hold. The tracker never blocks you from recording real holdings, but when an issuer or instrument type goes over its cap it asks you to acknowledge the breach before proceeding, and logs which cap, the percentage and the timestamp in Change History. This applies to both the per-issuer cap and the per-type cap, and only ever to actual recorded holdings - never to the engine's projected sweeps." },
  // ── Round 101: Part 8 — comprehensive glossary expansion ──
  // General
  { id: "portfolio", term: "Portfolio", def: "The collection of all your savings and investments tracked together toward a single goal — MMF accounts, bank deposits, government securities and market assets combined." },
  { id: "goal", term: "Goal", def: "The specific financial target you are saving toward — for example 'KES 5,000,000 for a car in 12 months'. The entire tracker is built around reaching this goal on time." },
  { id: "target-amount", term: "Target amount", def: "The exact KES figure you need by your goal date. Every projection, scenario and allocation decision is measured against this number." },
  { id: "horizon", term: "Horizon", def: "The number of months from today until your goal date. A shorter horizon means less time to compound and less room for locked instruments." },
  { id: "contribution", term: "Contribution", def: "The money you add to the plan each period (usually monthly). It lands in the primary MMF first, then gets swept into higher-yielding instruments if eligible." },
  { id: "projected", term: "Projected", def: "A future row in the Ledger that shows what the engine expects to happen — contributions, sweeps, maturities and interest — based on your current plan. It has not happened yet." },
  { id: "actual", term: "Actual", def: "A past row in the Ledger that records what really happened — real deposits, real maturities, real interest credited. Actual rows override projections for the same month." },
  { id: "market-value", term: "Market value", def: "What an asset is worth at today's price if you sold it now. For listed equities and REITs this changes daily; for fixed-income held to maturity it equals face value plus accrued interest." },
  { id: "source-as-of", term: "Source as-of date", def: "The date the data in a catalogue row was last confirmed from its original source (e.g. a fund factsheet dated 30 Jun 2026). If this date is old, the row may be stale." },
  { id: "stale-source", term: "Stale source", def: "A catalogue row whose source as-of date is older than the expected refresh cycle — for example an MMF rate not updated in 30+ days. Stale data may no longer reflect reality." },
  { id: "verification", term: "Verification", def: "A human check confirming that a catalogue figure matches its original source document. Verified fields show a shield icon; unverified fields may still be AI-extracted and awaiting confirmation." },
  { id: "clean-price", term: "Clean price", def: "The price of a bond excluding any accrued coupon interest. When you buy a bond between coupon dates you pay the clean price plus accrued interest (the dirty price)." },
  { id: "dirty-price", term: "Dirty price", def: "Clean price plus accrued interest — the actual cash amount you pay to buy a bond between coupon dates. Also called the full price or settlement price." },
  // MMFs
  { id: "fund-manager", term: "Fund manager", def: "The licensed company that operates the money market fund — for example Cytonn, CIC, ICEA Lion. They invest pooled money, charge a management fee and report the net yield." },
  { id: "management-fee", term: "Management fee", def: "The annual percentage the fund manager deducts from the fund's gross earnings before reporting the net EAR to you. A lower fee means more of the gross yield reaches your pocket." },
  { id: "aum", term: "AUM (Assets Under Management)", def: "The total amount of money all investors have placed in a fund. Larger AUM can mean more stability and bargaining power, but is not a guarantee of higher returns." },
  { id: "crediting-frequency", term: "Crediting frequency", def: "How often the fund adds earned interest to your balance — daily, weekly or monthly. Daily crediting means you compound faster." },
  { id: "daily-accrual", term: "Daily accrual", def: "The interest your MMF balance earns each day, calculated as (balance × daily rate). It accumulates and is credited at the fund's crediting frequency." },
  { id: "withdrawal-notice", term: "Withdrawal notice", def: "The number of days you must wait between requesting a withdrawal and receiving the cash — typically T+1 to T+3 for Kenyan MMFs." },
  { id: "fund-composition", term: "Fund composition", def: "The breakdown of where the MMF invests its pooled money — government securities, bank deposits, corporate paper, etc. A higher government allocation is generally safer." },
  { id: "gov-bucket", term: "Government securities bucket", def: "The share of an MMF's portfolio invested in Treasury bills and bonds. Government paper is sovereign-backed and considered the safest component." },
  { id: "bank-bucket", term: "Bank-deposit bucket", def: "The share of an MMF's portfolio placed in bank fixed deposits and call accounts. It earns competitive rates but carries the credit risk of the individual banks." },
  { id: "corporate-bucket", term: "Corporate paper bucket", def: "The share of an MMF's portfolio invested in short-term corporate debt (commercial paper). It usually offers higher yields but carries more credit risk than government or bank paper." },
  // CBK securities
  { id: "91-day-tbill", term: "91-day T-bill", def: "The shortest Treasury bill — you buy at a discount and receive face value 91 days later. Ideal for parking cash you need back in about three months." },
  { id: "182-day-tbill", term: "182-day T-bill", def: "A six-month Treasury bill. Slightly higher yield than the 91-day because your money is locked longer." },
  { id: "364-day-tbill", term: "364-day T-bill", def: "A one-year Treasury bill offering the highest T-bill yield. Your money is locked for nearly a full year." },
  { id: "discount-concept", term: "Discount (T-bill pricing)", def: "The difference between face value and what you pay. For a KES 100,000 T-bill bought at KES 96,000, the KES 4,000 discount is your entire return." },
  { id: "treasury-bond", term: "Treasury bond", def: "A longer-term government security (2–30 years) that pays semi-annual coupons and returns face value at maturity. Includes FXD (taxable) and IFB (tax-exempt) variants." },
  { id: "coupon-payment-date", term: "Coupon payment date", def: "The specific date a bond pays its semi-annual coupon. For example, a bond with coupon dates 15 Jan and 15 Jul pays you twice a year on those dates." },
  { id: "issue-number", term: "Issue number", def: "The unique identifier CBK assigns to each security — e.g. FXD1/2022/010 means the first 10-year fixed-coupon bond issued in 2022. Used to track and match holdings." },
  { id: "isin", term: "ISIN", def: "International Securities Identification Number — a 12-character global code (e.g. KE0000000001) that uniquely identifies a security across all markets and systems." },
  { id: "auction-date", term: "Auction date", def: "The date CBK holds the auction where investors bid for new Treasury bills or bonds. Results are published shortly after." },
  { id: "settlement-date", term: "Settlement date", def: "The date you actually pay for and receive a security — usually T+1 (one business day after the auction). Your holding starts earning from this date." },
  { id: "bid-deadline", term: "Bid deadline", def: "The cut-off time by which your bid must reach CBK for a particular auction. Late bids are rejected." },
  { id: "non-competitive-bid", term: "Non-competitive bid", def: "A bid where you accept whatever rate the auction produces (the weighted average). Guaranteed allocation up to KES 20 million — simplest way for retail investors to participate." },
  { id: "competitive-bid", term: "Competitive bid", def: "A bid where you specify the exact rate (or price) you want. If your rate is too high (greedy), your bid may be rejected. Used by institutional investors." },
  { id: "secondary-trading", term: "Secondary trading", def: "Buying or selling an already-issued government security on the secondary market (through a broker or DhowCSD) rather than at the original CBK auction." },
  { id: "reopening", term: "Reopening", def: "When CBK issues more of an existing bond (same issue number, coupon and maturity) rather than creating a new one. Reopened bonds trade at market price, which may differ from the original par." },
  { id: "dhowcsd", term: "DhowCSD", def: "The Central Securities Depository operated by the Nairobi Securities Exchange. It holds your government securities electronically and processes settlements, coupon payments and redemptions." },
  // Bank instruments
  { id: "notice-period", term: "Notice period", def: "The number of days you must give the bank before withdrawing from a call or notice deposit — e.g. 7 days, 30 days. During the notice period the money is still earning interest." },
  { id: "negotiated-rate", term: "Negotiated rate", def: "The actual interest rate you agreed with the bank, which may be higher than the published indicative rate — especially for larger deposits. This is what your holding earns." },
  { id: "payout-frequency", term: "Payout frequency", def: "How often the bank pays (or compounds) interest on your deposit — monthly, quarterly, at maturity, etc. More frequent payouts let you compound faster." },
  // Market assets
  { id: "equity", term: "Equity (stock)", def: "Ownership shares in a company listed on a stock exchange (e.g. NSE). Value rises and falls with the market — higher potential return but also higher risk than fixed income." },
  { id: "reit", term: "REIT (Real Estate Investment Trust)", def: "A listed fund that owns income-producing property and distributes most of its rental income to investors. Offers real-estate exposure without buying property directly." },
  { id: "etf", term: "ETF (Exchange-Traded Fund)", def: "A fund that tracks an index or basket of assets and trades on an exchange like a stock. Provides diversification in a single purchase." },
  { id: "nav", term: "NAV (Net Asset Value)", def: "The per-unit value of a fund's assets minus liabilities. For an MMF or ETF, the NAV is the price at which you buy or sell units." },
  { id: "dividend-yield", term: "Dividend yield", def: "Annual dividends paid per share divided by the share price, expressed as a percentage. Shows how much income a stock generates relative to its price." },
  { id: "distribution-yield", term: "Distribution yield", def: "The annualised income (dividends, interest, rent) a fund distributes to holders, divided by its current price. Similar to dividend yield but for funds." },
  { id: "trailing-return", term: "Trailing return", def: "The total return (price change plus income) over a past period — e.g. 12-month trailing return. It tells you what you would have earned if you held for that period." },
  { id: "fx-risk", term: "FX risk (currency risk)", def: "The risk that an offshore or USD-denominated asset loses value in KES terms when the shilling strengthens, even if the asset itself did not fall." },
  { id: "capital-risk", term: "Capital risk", def: "The risk that the market price of an asset falls below what you paid — you could sell at a loss. Fixed-income held to maturity has near-zero capital risk; equities have significant capital risk." },
  // Planning
  { id: "allocation", term: "Allocation", def: "How your total portfolio is divided across instrument types — e.g. 40% MMF, 30% T-bills, 20% bonds, 10% bank deposits. The engine optimises allocation to maximise yield within your constraints." },
  { id: "glide-path", term: "Glide path", def: "The planned shift in allocation over time — typically from growth instruments early on to liquid, safe instruments as the goal date approaches. Ensures money is accessible when you need it." },
  { id: "de-risking", term: "De-risking", def: "Gradually moving money from volatile or locked instruments into safe, liquid ones as the goal date nears — reducing the chance of a last-minute loss or liquidity crunch." },
  { id: "probability-band", term: "Probability band", def: "The range of possible outcomes (best case to worst case) shown on the Dashboard. For fixed-income-only plans the band is narrow; adding market assets widens it because prices fluctuate." },
  { id: "worst-case", term: "Worst case", def: "The lower bound of the probability band — what happens if market assets drop and rates fall. The plan should still be achievable even in this scenario." },
  { id: "best-case", term: "Best case", def: "The upper bound of the probability band — what happens if market assets rise and rates stay high. Do not count on this; it is the optimistic tail." },
  { id: "scenario", term: "Scenario", def: "A what-if projection that changes one variable (e.g. step-up amount) while holding everything else constant, so you can compare outcomes side by side." },
];


/** Fast lookup of a glossary entry by its stable id. */
export const GLOSSARY_BY_ID: Record<string, GlossaryEntry> = Object.fromEntries(
  GLOSSARY.map((g) => [g.id, g])
);

/** Get a definition string by id (empty string if unknown). */
export function glossaryDef(id: string): string {
  return GLOSSARY_BY_ID[id]?.def ?? "";
}
