#!/usr/bin/env python3
"""Compile the full KES 5M Tracker source code into a single markdown document."""
import os

ROOT = "/home/ubuntu/kes5m-tracker"
OUT = "/home/ubuntu/KES5M_Tracker_Full_Source_Code.md"

# Map extensions to markdown code-fence languages
LANG = {
    ".ts": "typescript",
    ".tsx": "tsx",
    ".css": "css",
    ".json": "json",
    ".html": "html",
    ".md": "markdown",
    ".js": "javascript",
}

# Ordered list of (section title, [relative file paths])
SECTIONS = [
    ("1. Project Configuration", [
        "package.json",
        "tsconfig.json",
        "vite.config.ts",
        "drizzle.config.ts",
        "components.json",
    ]),
    ("2. Database Schema & Relations", [
        "drizzle/schema.ts",
        "drizzle/relations.ts",
    ]),
    ("3. Shared Constants, Types & Accrual Math", [
        "shared/const.ts",
        "shared/types.ts",
        "shared/accrual.ts",
    ]),
    ("4. Server — Projection Engine", [
        "server/engine.ts",
    ]),
    ("5. Server — Database Helpers", [
        "server/db.ts",
    ]),
    ("6. Server — tRPC Routers", [
        "server/routers.ts",
    ]),
    ("7. Server — Storage Helper", [
        "server/storage.ts",
    ]),
    ("8. Server — Tests", [
        "server/engine.test.ts",
        "server/engine.regression.test.ts",
        "server/accrual.test.ts",
        "server/taxBreakdown.test.ts",
        "server/auth.logout.test.ts",
    ]),
    ("9. Client — App Entry & Routing", [
        "client/index.html",
        "client/src/main.tsx",
        "client/src/App.tsx",
        "client/src/index.css",
    ]),
    ("10. Client — Contexts", [
        "client/src/contexts/PortfolioContext.tsx",
        "client/src/contexts/DepositDrawerContext.tsx",
        "client/src/contexts/ThemeContext.tsx",
    ]),
    ("11. Client — Hooks", [
        "client/src/hooks/useSelectedFund.ts",
        "client/src/hooks/useComposition.ts",
    ]),
    ("12. Client — Libraries", [
        "client/src/lib/trpc.ts",
        "client/src/lib/format.ts",
        "client/src/lib/utils.ts",
        "client/src/const.ts",
    ]),
    ("13. Client — Custom Components", [
        "client/src/components/AppShell.tsx",
        "client/src/components/PortfolioSelector.tsx",
        "client/src/components/DepositDrawer.tsx",
        "client/src/components/UpdateRatesPanel.tsx",
    ]),
    ("14. Client — Pages", [
        "client/src/pages/Home.tsx",
        "client/src/pages/Dashboard.tsx",
        "client/src/pages/MmfFunds.tsx",
        "client/src/pages/OtherAssets.tsx",
        "client/src/pages/Deposits.tsx",
        "client/src/pages/Ledger.tsx",
        "client/src/pages/Contributions.tsx",
        "client/src/pages/Securities.tsx",
        "client/src/pages/Scenarios.tsx",
        "client/src/pages/Settings.tsx",
        "client/src/pages/GettingStarted.tsx",
        "client/src/pages/MmfAccrual.tsx",
        "client/src/pages/TaxSummary.tsx",
        "client/src/pages/MmfStrategy.tsx",
        "client/src/pages/BankInstruments.tsx",
        "client/src/pages/PortfolioReview.tsx",
        "client/src/pages/NotFound.tsx",
    ]),
    ("15. Project TODO / Change Log", [
        "todo.md",
    ]),
]

def lang_for(path):
    _, ext = os.path.splitext(path)
    return LANG.get(ext, "")

def main():
    parts = []
    parts.append("# KES 5M Investment Tracker — Full Source Code\n")
    parts.append(
        "This document contains the complete source code for the **KES 5M Investment Tracker**, "
        "a personal investment-planning web application that projects a 10-year journey to KES 5,000,000 "
        "across Money Market Funds (MMFs), CBK Treasury Bills, Infrastructure Finance Bonds (IFBs), and "
        "Fixed Coupon Bonds (FXDs).\n\n"
        "**Stack:** React 19 + Tailwind CSS 4 + Express 4 + tRPC 11 + Drizzle ORM (MySQL/TiDB), "
        "with Manus OAuth authentication.\n\n"
        "> Framework plumbing under `server/_core/` and the shadcn/ui primitives under "
        "`client/src/components/ui/` are auto-generated by the template and are omitted here. "
        "Only the application-specific code is included.\n"
    )

    # Table of contents
    parts.append("\n## Table of Contents\n")
    for title, _ in SECTIONS:
        anchor = title.lower().replace(".", "").replace("—", "").replace("/", "").replace("&", "").strip().replace("  ", " ").replace(" ", "-")
        parts.append(f"- [{title}](#{anchor})")
    parts.append("\n---\n")

    for title, files in SECTIONS:
        parts.append(f"\n## {title}\n")
        for rel in files:
            full = os.path.join(ROOT, rel)
            if not os.path.exists(full):
                parts.append(f"\n### `{rel}`\n\n_(file not found — skipped)_\n")
                continue
            with open(full, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
            lang = lang_for(rel)
            parts.append(f"\n### `{rel}`\n")
            # Use a long fence to avoid collision with backticks inside content
            fence = "````"
            while fence in content:
                fence += "`"
            parts.append(f"{fence}{lang}\n{content}\n{fence}\n")

    out = "\n".join(parts)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"Wrote {OUT}")
    print(f"Total size: {len(out):,} chars, {out.count(chr(10)):,} lines")

if __name__ == "__main__":
    main()
