/**
 * Expansion Brief — Part 2 reference seed for the Opportunity Catalog, extended in
 * Part 7.1 with PER-FIGURE provenance.
 *
 * These are NEUTRAL, SOURCED, TIMESTAMPED facts pulled from public sources. They
 * are stored verbatim — no ranking, no "best/top," no quality score — and every
 * row is flagged `unverified: true` because the figures are gathered from public
 * pages and may be delayed or inaccurate. The catalog presents the universe; the
 * user narrows it.
 *
 * Part 7.1: in addition to the row-level dataSource/dataAsOf/unverified, every
 * INDIVIDUAL figure (price, yield, coupon, tenor, maturity, distribution, FX,
 * expense, trailing return) now carries its OWN provenance entry in
 * `fieldProvenance` — source, sourceUrl, asOf, fetchedAt and a verification state.
 * The backfill below derives each figure's provenance from the row's source/asOf
 * via `buildSeedProvenance()` so NO number changes; only the trust metadata is
 * promoted from per-row to per-figure. All seeded figures start
 * `scraped_unverified` (no human has checked them yet); a person raises that state
 * later through the verify mutation.
 *
 * Source notes (captured at seed time, shown inline in the UI):
 *  - NSE equity closes: nse.co.ke / mystocks.co.ke (late Jun 2026).
 *  - Safaricom final dividend KES 1.15 announced 07-May-2026 (NSE).
 *  - ILAM Fahari I-REIT trailing return: african-markets.com (FAHR).
 *  - SanlamAllianz MMF daily yield 8.45% as of 24-Jun-2026 (manager site).
 *  - CBK securities: indicative CBK auction/secondary levels (DhowCSD).
 *  - Offshore funds: indicative published figures; FX/jurisdiction caveats apply.
 */
import type { InsertOpportunity } from "../drizzle/schema";
import { buildSeedProvenance, summariseState, type FieldProvenanceMap } from "../shared/provenance";

/** A fixed as-of date for the seed batch (UTC noon to avoid TZ edge cases). */
const ASOF = new Date("2026-06-26T12:00:00Z");

/** Canonical public source URLs reused across rows from the same origin. */
const URL_NSE = "https://www.nse.co.ke/share-price/";
const URL_MYSTOCKS = "https://live.mystocks.co.ke/";
const URL_AFRICAN_MARKETS = "https://www.african-markets.com/en/stock-markets/nse";
const URL_SANLAM = "https://www.sanlaminvestments.com/daily-prices";
const URL_CBK_TBONDS = "https://www.centralbank.go.ke/securities/treasury-bonds/";
const URL_CBK_TBILLS = "https://www.centralbank.go.ke/securities/treasury-bills/";

/**
 * One place that turns a row's figure columns + row-level provenance into a
 * per-figure FieldProvenanceMap, then stamps the matching row summary state.
 * `distribution` is mapped from the row's yield when the yieldKind names a
 * distribution (REITs/funds) so the distribution figure gets its own entry.
 */
type SeedRow = Omit<InsertOpportunity, "fieldProvenance" | "verificationState"> & {
  /** Per-figure source URL override (defaults applied per asset class below). */
  sourceUrl?: string | null;
  /** Distinct distribution figure where the headline yield IS a distribution. */
  distributionPct?: string | null;
  /** Explicit FX figure (offshore rows that record a USD/KES used to express KES). */
  fxRate?: string | null;
};

function withProvenance(row: SeedRow): InsertOpportunity {
  const { sourceUrl, distributionPct, fxRate, ...rest } = row;
  const map: FieldProvenanceMap = buildSeedProvenance({
    source: rest.dataSource ?? null,
    sourceUrl: sourceUrl ?? null,
    asOf: rest.dataAsOf ?? null,
    figures: {
      price: rest.lastPrice ?? null,
      // Coupon vs yield: gov coupon paper records the figure as a coupon.
      coupon: rest.assetClass === "gov_coupon" ? (rest.yieldPct ?? null) : null,
      yield: rest.assetClass === "gov_coupon" ? null : (rest.yieldPct ?? null),
      distribution: distributionPct ?? null,
      tenor: rest.tenorYears ?? null,
      maturity: rest.maturityDate ?? null,
      expense: rest.expenseRatioPct ?? null,
      trailingReturn: rest.trailingReturnPct ?? null,
      fx: fxRate ?? null,
    },
  });
  return {
    ...rest,
    fieldProvenance: map,
    verificationState: summariseState(map),
  };
}

const RAW_SEED: SeedRow[] = [
  // ── Equities (price-driven) ────────────────────────────────────────────────
  {
    ref: "NSE:SCOM",
    name: "Safaricom PLC",
    assetClass: "equity",
    issuer: "Safaricom PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "18.50",
    trailingReturnPct: "12.4000",
    yieldPct: "6.2000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    factNote: "Final dividend of KES 1.15 announced 07-May-2026; books closure 04-Aug-2026.",
    dataSource: "NSE / mystocks.co.ke daily close",
    sourceUrl: URL_NSE,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:KCB",
    name: "KCB Group PLC",
    assetClass: "equity",
    issuer: "KCB Group PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "76.0000",
    trailingReturnPct: "31.0000",
    yieldPct: "5.2000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    factNote: "52-week range 44.00–80.25 per african-markets.com.",
    dataSource: "mystocks.co.ke realtime quote (26-Jun-2026)",
    sourceUrl: URL_MYSTOCKS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:EQTY",
    name: "Equity Group Holdings PLC",
    assetClass: "equity",
    issuer: "Equity Group Holdings PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "52.0000",
    trailingReturnPct: "24.0000",
    yieldPct: "8.1000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    dataSource: "NSE daily market report (02-Jun-2026)",
    sourceUrl: URL_NSE,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:EABL",
    name: "East African Breweries PLC",
    assetClass: "equity",
    issuer: "East African Breweries PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "168.0000",
    trailingReturnPct: "9.5000",
    yieldPct: "4.4000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    factNote: "Interim dividend KES 1.00/share for HY2026 (NSE announcement).",
    dataSource: "NSE / mystocks.co.ke daily close",
    sourceUrl: URL_NSE,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:COOP",
    name: "Co-operative Bank of Kenya PLC",
    assetClass: "equity",
    issuer: "Co-operative Bank of Kenya PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "16.5000",
    trailingReturnPct: "22.0000",
    yieldPct: "9.1000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    factNote: "Final dividend KES 1.50/share for FY2025 (NSE announcement).",
    dataSource: "mystocks.co.ke realtime quote (26-Jun-2026)",
    sourceUrl: URL_MYSTOCKS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:ABSA",
    name: "Absa Bank Kenya PLC",
    assetClass: "equity",
    issuer: "Absa Bank Kenya PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "18.9000",
    trailingReturnPct: "33.0000",
    yieldPct: "8.7000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    dataSource: "NSE / mystocks.co.ke daily close",
    sourceUrl: URL_NSE,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:SBIC",
    name: "Stanbic Holdings PLC",
    assetClass: "equity",
    issuer: "Stanbic Holdings PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "158.0000",
    trailingReturnPct: "26.0000",
    yieldPct: "12.6000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    dataSource: "NSE / mystocks.co.ke daily close",
    sourceUrl: URL_NSE,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:BAT",
    name: "British American Tobacco Kenya PLC",
    assetClass: "equity",
    issuer: "British American Tobacco Kenya PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "385.0000",
    trailingReturnPct: "-3.2000",
    yieldPct: "13.0000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    factNote: "High payout ratio; dividend cover is thin — income, not growth.",
    dataSource: "NSE / mystocks.co.ke daily close",
    sourceUrl: URL_NSE,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:NCBA",
    name: "NCBA Group PLC",
    assetClass: "equity",
    issuer: "NCBA Group PLC",
    currency: "KES",
    market: "NSE",
    lastPrice: "49.5000",
    trailingReturnPct: "20.0000",
    yieldPct: "9.6000",
    yieldKind: "dividend yield (indicative)",
    liquidity: "daily",
    dataSource: "mystocks.co.ke realtime quote (26-Jun-2026)",
    sourceUrl: URL_MYSTOCKS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },

  // ── REIT (price-driven) ──────────────────────────────────────────────────
  {
    ref: "NSE:FAHR",
    name: "ILAM Fahari I-REIT",
    assetClass: "reit",
    issuer: "ICEA Lion Asset Management",
    currency: "KES",
    market: "NSE",
    lastPrice: "11.0000",
    trailingReturnPct: "-5.6500",
    yieldPct: "6.4000",
    yieldKind: "distribution yield (indicative)",
    // The REIT headline yield IS a distribution — give it its own figure too.
    distributionPct: "6.4000",
    liquidity: "daily",
    factNote: "Distribution of KES 0.70/unit declared for FY2023; 1Y total return -5.65%.",
    dataSource: "african-markets.com (FAHR)",
    sourceUrl: URL_AFRICAN_MARKETS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:ACRN-DREIT",
    name: "Acorn Student Accommodation D-REIT",
    assetClass: "reit",
    issuer: "Acorn Investment Management",
    currency: "KES",
    market: "NSE (USP)",
    lastPrice: "23.7000",
    trailingReturnPct: "7.8000",
    yieldPct: "5.0000",
    yieldKind: "distribution yield (indicative)",
    distributionPct: "5.0000",
    liquidity: "term",
    factNote: "Development REIT (Qwetu/Qejani); restricted/unquoted segment — limited liquidity.",
    dataSource: "Acorn D-REIT NAV statement (indicative)",
    sourceUrl: URL_AFRICAN_MARKETS,
    dataAsOf: new Date("2026-03-31T12:00:00Z"),
    unverified: true,
    active: true,
  },
  {
    ref: "NSE:ACRN-IREIT",
    name: "Acorn Student Accommodation I-REIT",
    assetClass: "reit",
    issuer: "Acorn Investment Management",
    currency: "KES",
    market: "NSE (USP)",
    lastPrice: "21.4000",
    trailingReturnPct: "9.2000",
    yieldPct: "7.2000",
    yieldKind: "distribution yield (indicative)",
    distributionPct: "7.2000",
    liquidity: "term",
    factNote: "Income REIT holding stabilised Acorn assets; distributes rental income.",
    dataSource: "Acorn I-REIT NAV statement (indicative)",
    sourceUrl: URL_AFRICAN_MARKETS,
    dataAsOf: new Date("2026-03-31T12:00:00Z"),
    unverified: true,
    active: true,
  },

  // ── Money-market funds (cash_mmf) ──────────────────────────────────────────
  {
    ref: "MMF:SANLAM-MMF",
    name: "SanlamAllianz Money Market Fund",
    assetClass: "cash_mmf",
    issuer: "Sanlam Allianz Investments",
    currency: "KES",
    market: "Unit trust",
    yieldPct: "8.4500",
    yieldKind: "daily effective annual yield (gross)",
    expenseRatioPct: "1.2000",
    liquidity: "daily",
    factNote: "Daily yield published on the manager fact sheet; gross of 15% WHT.",
    dataSource: "Sanlam Allianz Investments site (24-Jun-2026)",
    sourceUrl: URL_SANLAM,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "MMF:CIC-MMF",
    name: "CIC Money Market Fund",
    assetClass: "cash_mmf",
    issuer: "CIC Asset Management",
    currency: "KES",
    market: "Unit trust",
    yieldPct: "8.2000",
    yieldKind: "effective annual yield (gross)",
    expenseRatioPct: "1.5000",
    liquidity: "daily",
    factNote: "Largest MMF by market share per industry data.",
    dataSource: "Industry MMF yield round-up (Apr 2026)",
    sourceUrl: null,
    dataAsOf: new Date("2026-04-28T12:00:00Z"),
    unverified: true,
    active: true,
  },
  {
    ref: "MMF:NCBA-MMF",
    name: "NCBA Money Market Fund",
    assetClass: "cash_mmf",
    issuer: "NCBA Investment Bank",
    currency: "KES",
    market: "Unit trust",
    yieldPct: "8.9000",
    yieldKind: "effective annual yield (gross)",
    expenseRatioPct: "2.0000",
    liquidity: "daily",
    factNote: "Daily-accrual MMF; yield quoted gross of 15% WHT.",
    dataSource: "NCBA unit trust fact sheet (Jun 2026)",
    sourceUrl: null,
    dataAsOf: new Date("2026-06-20T12:00:00Z"),
    unverified: true,
    active: true,
  },
  {
    ref: "MMF:ETICA-MMF",
    name: "Etica Money Market Fund",
    assetClass: "cash_mmf",
    issuer: "Etica Capital",
    currency: "KES",
    market: "Unit trust",
    yieldPct: "10.5000",
    yieldKind: "effective annual yield (gross)",
    expenseRatioPct: "2.0000",
    liquidity: "daily",
    factNote: "Among the highest-quoted MMF yields; verify the quote and WHT treatment.",
    dataSource: "Etica Capital fact sheet (indicative)",
    sourceUrl: null,
    dataAsOf: new Date("2026-06-15T12:00:00Z"),
    unverified: true,
    active: true,
  },
  {
    ref: "MMF:OLDMUTUAL-MMF",
    name: "Old Mutual Money Market Fund",
    assetClass: "cash_mmf",
    issuer: "Old Mutual Investment Group",
    currency: "KES",
    market: "Unit trust",
    yieldPct: "8.1000",
    yieldKind: "effective annual yield (gross)",
    expenseRatioPct: "1.8000",
    liquidity: "daily",
    factNote: "Established manager; daily-accrual MMF, gross of 15% WHT.",
    dataSource: "Old Mutual unit trust fact sheet (indicative)",
    sourceUrl: null,
    dataAsOf: new Date("2026-06-12T12:00:00Z"),
    unverified: true,
    active: true,
  },

  // ── Government coupon paper (gov_coupon) ────────────────────────────────────
  {
    ref: "CBK:IFB1-2026",
    name: "Infrastructure Bond IFB1/2026/15",
    assetClass: "gov_coupon",
    issuer: "Central Bank of Kenya",
    currency: "KES",
    market: "CBK",
    yieldPct: "13.5000",
    yieldKind: "coupon (tax-exempt)",
    tenorYears: "15.00",
    maturityDate: new Date("2041-03-01T12:00:00Z"),
    liquidity: "term",
    factNote: "Infrastructure bond; coupon is tax-exempt for qualifying holders.",
    dataSource: "CBK auction results (indicative)",
    sourceUrl: URL_CBK_TBONDS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "CBK:FXD-2026-10Y",
    name: "Treasury Bond FXD1/2026/10",
    assetClass: "gov_coupon",
    issuer: "Central Bank of Kenya",
    currency: "KES",
    market: "CBK",
    yieldPct: "14.2000",
    yieldKind: "coupon",
    tenorYears: "10.00",
    maturityDate: new Date("2036-06-01T12:00:00Z"),
    liquidity: "term",
    dataSource: "CBK secondary market (indicative)",
    sourceUrl: URL_CBK_TBONDS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "CBK:FXD-2024-05Y",
    name: "Treasury Bond FXD1/2024/05",
    assetClass: "gov_coupon",
    issuer: "Central Bank of Kenya",
    currency: "KES",
    market: "CBK",
    yieldPct: "13.8000",
    yieldKind: "coupon",
    tenorYears: "5.00",
    maturityDate: new Date("2029-02-01T12:00:00Z"),
    liquidity: "term",
    dataSource: "CBK secondary market (indicative)",
    sourceUrl: URL_CBK_TBONDS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "CBK:FXD-2023-02Y",
    name: "Treasury Bond FXD1/2023/02",
    assetClass: "gov_coupon",
    issuer: "Central Bank of Kenya",
    currency: "KES",
    market: "CBK",
    yieldPct: "13.0000",
    yieldKind: "coupon",
    tenorYears: "2.00",
    maturityDate: new Date("2027-09-01T12:00:00Z"),
    liquidity: "term",
    factNote: "Shorter-dated fixed-coupon paper; lower duration risk than the 10Y/15Y.",
    dataSource: "CBK secondary market (indicative)",
    sourceUrl: URL_CBK_TBONDS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "CBK:IFB1-2025",
    name: "Infrastructure Bond IFB1/2025/14",
    assetClass: "gov_coupon",
    issuer: "Central Bank of Kenya",
    currency: "KES",
    market: "CBK",
    yieldPct: "13.2000",
    yieldKind: "coupon (tax-exempt)",
    tenorYears: "14.00",
    maturityDate: new Date("2039-02-01T12:00:00Z"),
    liquidity: "term",
    factNote: "Tax-exempt infrastructure bond; widely held by Kenyan retail and pensions.",
    dataSource: "CBK auction results (indicative)",
    sourceUrl: URL_CBK_TBONDS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },

  // ── Government discount paper (gov_discount) ────────────────────────────────
  {
    ref: "CBK:TBILL-364",
    name: "364-Day Treasury Bill",
    assetClass: "gov_discount",
    issuer: "Central Bank of Kenya",
    currency: "KES",
    market: "CBK",
    yieldPct: "11.9000",
    yieldKind: "discount yield",
    tenorYears: "1.00",
    liquidity: "term",
    dataSource: "CBK weekly T-bill auction (indicative)",
    sourceUrl: URL_CBK_TBILLS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "CBK:TBILL-182",
    name: "182-Day Treasury Bill",
    assetClass: "gov_discount",
    issuer: "Central Bank of Kenya",
    currency: "KES",
    market: "CBK",
    yieldPct: "11.4000",
    yieldKind: "discount yield",
    tenorYears: "0.50",
    liquidity: "term",
    dataSource: "CBK weekly T-bill auction (indicative)",
    sourceUrl: URL_CBK_TBILLS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "CBK:TBILL-91",
    name: "91-Day Treasury Bill",
    assetClass: "gov_discount",
    issuer: "Central Bank of Kenya",
    currency: "KES",
    market: "CBK",
    yieldPct: "10.9000",
    yieldKind: "discount yield",
    tenorYears: "0.25",
    liquidity: "term",
    factNote: "Shortest government paper; auctioned weekly, settles T+1.",
    dataSource: "CBK weekly T-bill auction (indicative)",
    sourceUrl: URL_CBK_TBILLS,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },

  // ── Offshore funds (price-driven, FX-exposed) ──────────────────────────────
  {
    ref: "OFF:VWRA",
    name: "Vanguard FTSE All-World UCITS ETF (USD)",
    assetClass: "offshore_fund",
    issuer: "Vanguard",
    currency: "USD",
    market: "Offshore (LSE)",
    lastPrice: "142.5000",
    trailingReturnPct: "11.2000",
    expenseRatioPct: "0.2200",
    liquidity: "daily",
    factNote: "USD-denominated; KES returns depend on the USD/KES rate (FX risk).",
    dataSource: "Public ETF fact sheet (indicative)",
    sourceUrl: null,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "OFF:CSPX",
    name: "iShares Core S&P 500 UCITS ETF (USD)",
    assetClass: "offshore_fund",
    issuer: "BlackRock / iShares",
    currency: "USD",
    market: "Offshore (LSE)",
    lastPrice: "605.0000",
    trailingReturnPct: "13.4000",
    expenseRatioPct: "0.0700",
    liquidity: "daily",
    factNote: "Accumulating S&P 500 tracker; USD-denominated, so KES returns carry FX risk.",
    dataSource: "Public ETF fact sheet (indicative)",
    sourceUrl: null,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
  {
    ref: "OFF:SPY-MMF-USD",
    name: "USD Money Market Fund (offshore)",
    assetClass: "offshore_fund",
    issuer: "Offshore manager",
    currency: "USD",
    market: "Offshore",
    yieldPct: "4.6000",
    yieldKind: "7-day yield (indicative)",
    expenseRatioPct: "0.1500",
    liquidity: "daily",
    factNote: "USD-denominated; subject to FX and treaty/jurisdiction tax treatment.",
    dataSource: "Public fund fact sheet (indicative)",
    sourceUrl: null,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },

  // ── Bank product (bank_deposit) ─────────────────────────────────────────────
  {
    ref: "BANK:FD-12M",
    name: "12-Month Fixed Deposit (representative)",
    assetClass: "bank_deposit",
    issuer: "Tier-1 commercial bank",
    currency: "KES",
    market: "Bank",
    yieldPct: "10.0000",
    yieldKind: "fixed deposit rate (gross)",
    tenorYears: "1.00",
    liquidity: "term",
    factNote: "Representative tier-1 rate; KDIC-insured up to the statutory limit.",
    dataSource: "Bank published deposit rates (indicative)",
    sourceUrl: null,
    dataAsOf: ASOF,
    unverified: true,
    active: true,
  },
];

export const OPPORTUNITY_SEED: InsertOpportunity[] = RAW_SEED.map(withProvenance);
